base: "/rds/project/rs2099/rds-rs2099-toxgenomics/sita_eisa"
homo_sapiens:
  fasta: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/GRCh38.primary_assembly.genome.fa"
  gtf: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/gencode.v34.annotation.gtf"
  gene_bed: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/hg38_Gencode_V24.bed"
mus_musculus:
  fasta: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/GRCm38.primary_assembly.genome.fa"
  gtf: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/gencode.vM25.annotation.gtf"
  gene_bed: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/mm10_Gencode_VM18.bed"
caenorhabditis_elegans:
  fasta: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/c_elegans/Caenorhabditis_elegans.WBcel235.dna.toplevel.fa"
  gtf: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/c_elegans/Caenorhabditis_elegans.WBcel235.101.gtf"
  gene_bed: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/c_elegans/WBcel235.ensembl.bed"
drosophila_melanogaster:
  fasta: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/drosophila/dmel-all-chromosome-r6.36.fa"
  gtf: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/drosophila/dmel-all-r6.36.gtf"
  gene_bed: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/drosophila/BDGP6.ensembl.bed"
