base: "/rds/project/rs2099/rds-rs2099-toxgenomics/sita_eisa"
fasta:
  human: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/GRCh38.primary_assembly.genome.fa"
  mouse: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/GRCm38.primary_assembly.genome.fa"
  c_elegans: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/c_elegans/Caenorhabditis_elegans.WBcel235.dna.toplevel.fa"
gtf:
  human: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/gencode.v34.annotation.gtf"
  mouse: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/gencode.vM25.annotation.gtf"
  c_elegans: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/c_elegans/Caenorhabditis_elegans.WBcel235.101.gtf"
bed:
  human: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/hg38_Gencode_V24.bed"
  mouse: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/mm10_Gencode_VM18.bed"
  c_elegans: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/c_elegans/WBcel235.ensembl.bed"
txdb:
  human: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/txdb.hg38.gencode.v34.sqlite"
  mouse: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/txdb.gencode.vM25.annotation.sqlite"
  c_elegans: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/c_elegans/txdb.c_elegans.WBcel235.101.sqlite"
