base: "/rds/project/rs2099/rds-rs2099-toxgenomics/sita_eisa"
<<<<<<< HEAD
homo_sapiens:
  fasta: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/GRCh38.primary_assembly.genome.fa"
  gtf: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/gencode.v34.annotation.gtf"
  gene_bed: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/hg38_Gencode_V24.bed"
mus_musculus:
  fasta: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/GRCm38.primary_assembly.genome.fa"
  gtf: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/gencode.vM25.annotation.gtf"
  gene_bed: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/mm10_Gencode_VM18.bed"
caenorhabditis_elegans:
  fasta: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/c_elegans/Caenorhabditis_elegans.WBcel235.dna.toplevel.fa"
  gtf: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/c_elegans/Caenorhabditis_elegans.WBcel235.101.gtf"
  gene_bed: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/c_elegans/WBcel235.ensembl.bed"
drosophila_melanogaster:
  fasta: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/drosophila/dmel-all-chromosome-r6.36.fa"
  gtf: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/drosophila/dmel-all-r6.36.gtf"
  gene_bed: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/drosophila/BDGP6.ensembl.bed"
=======
fasta:
  homo_sapiens: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/GRCh38.primary_assembly.genome.fa"
  mus_musculus: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/GRCm38.primary_assembly.genome.fa"
  caenorhabditis_elegans: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/c_elegans/Caenorhabditis_elegans.WBcel235.dna.toplevel.fa"
  drosophila_melanogaster: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/drosophila/Drosophila_melanogaster.BDGP6.28.dna.toplevel.fa"
gtf:
  homo_sapiens: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/gencode.v34.annotation.gtf"
  mus_musculus: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/gencode.vM25.annotation.gtf"
  caenorhabditis_elegans: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/c_elegans/Caenorhabditis_elegans.WBcel235.101.gtf"
  drosophila_melanogaster: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/drosophila/Drosophila_melanogaster.BDGP6.28.101.gtf"
bed:
  homo_sapiens: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/hg38_Gencode_V24.bed"
  mus_musculus: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/mm10_Gencode_VM18.bed"
  caenorhabditis_elegans: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/c_elegans/WBcel235.ensembl.bed"
  drosophila_melanogaster: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/drosophila/BDGP6.ensembl.bed"
txdb:
  homo_sapiens: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/txdb.hg38.gencode.v34.sqlite"
  mus_musculus: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/txdb.gencode.vM25.annotation.sqlite"
  caenorhabditis_elegans: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/c_elegans/txdb.c_elegans.WBcel235.101.sqlite"
  drosophila_melanogaster: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/drosophila/Drosophila_melanogaster.BDGP6.28.101.sqlite"
>>>>>>> 659a09d652073412978158006cc0255ee77b6d5c
